### ISSUE TITLE
Build instructions are outdated

### ISSUE THREAD

**Issue by jgoguen** [astrada/ocamlfuse#13]
The README still says to use `cd lib; make; make install` to build. But with moving to Dune that won't work anymore.

I tried simply running `dune build @install` but that doesn't work either: it complains "Could not query camlidl lib path", but I have camlidl installed.

**Comment by astrada** [comment]
I updated the README. Let me know if it's enough or there is something to explain more clearly.

> I tried simply running `dune build @install` but that doesn't work either: it complains "Could not query camlidl lib path", but I have camlidl installed.

The dune PR uses opam to check for `camlidl` path. So, if you install camlidl with opam, `dune build @install` should work.

**Comment by jgoguen** [comment]
Sorry for the delay. The updated build instructions work. I'm still not having `camlidl` detected, but it's installed from an OS (Fedora) package rather than opam.

Could `ocamlfind` or `dune`'s library resolution be used to find libraries if `opam` doesn't find them? `ocamlfind` shows `camlidl` and says it's installed in `/usr/lib64/ocaml`. Following [the directions from `dune` for finding library search paths](https://jbuilder.readthedocs.io/en/latest/usage.html#finding-external-libraries), `/usr/lib64/ocaml` is the only path it reports and should be the one it uses to look for all external libraries.

**Comment by astrada** [comment]
@constfun, sorry to bother you, do you think it's possible to do what @jgoguen is asking?

**Comment by RiderALT** [comment]
I also caught this problem for the case when the camlide was installed in the system place.
$ opam config var camlidl:lib
[ERROR] Opam has not been initialised, please run `opam init'
$ rpm -q ocaml-camlidl
ocaml-camlidl-1.06-alt1.x86_64
 rpm -q ocaml-camlidl-devel
ocaml-camlidl-devel-1.06-alt1.x86_64

$ ocamlfind query camlidl
/usr/lib64/ocaml

**Comment by astrada** [comment]
With commit e35e76bee3b06806256b5bfca108b7697267cd5c, I've added an `ocamlfind` failover for `camlidl`. If you want you can test it.

**Comment by jgoguen** [comment]
Now it complains there's no make target `install`.

**Comment by astrada** [comment]
> Now it complains there's no make target install.

What command returns that error?

**Comment by JoeNotCharles** [comment]
I have the same issue on debian, even with the "ocamlfind failover"

$ git log --oneline|head -1
e35e76b Add ocamlfind failover for camlidl
$ opam config var camlidl:lib
[ERROR] Variable camlidl:lib not found
$ ocamlfind query camlidl
/usr/lib/ocaml
$ dpkg -l|grep camlidl
ii  camlidl                                1.05-15.1                            amd64        Stub code generator for Objective Caml
$ dune external-lib-deps --missing @install
Error: The following libraries are missing in the default context:
- camlidl
Hint: try: opam install camlidl

("opam install" consistently locks up on my system so I'm using the system packages exclusively.)

It seems that dune is not looking at lib/config/discover.ml at all. I had to take camlidl out of the libraries list in lib/dune to continue.

**Comment by astrada** [comment]
The debian package is not compatible with dune (the problem is that the META file is stored in `/usr/lib/ocaml/METAS/META.camlidl` and dune doesn't check that path). I patched the package for Ubuntu, you can find it [here](https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta/+packages). Maybe you can install it on debian too.

**Comment by meabolex** [comment]
Just a note if you have this problem, if you're trying to use root for your sandbox, I consistently get the error above ("Could not query camlidl lib path").  I think the problem is that there's a random warning text telling you that you shouldn't run your sandbox as root and it breaks the build.  I created a separate non-root user for opam and did the sandboxed build there with no problems.

**Comment by sergiomb2** [comment]
The README still says to use cd lib; make; make install to build. But with moving to Dune that won't work anymore.

**Comment by sergiomb2** [comment]
dune doesn't exist in Fedora

**Comment by astrada** [comment]
Have you tried downloading the package e.g. from here: https://pkgs.org/download/ocaml-dune?

**Comment by sergiomb2** [comment]
ok after install ocaml-dune
```
dune build @install

File "lib/dune", line 10, characters 0-135:
10 | (rule
11 |  (targets fuse.libs.sexp fuse.cflags.sexp camlidl.libs.sexp)
12 |  (deps (:discover config/discover.exe))
13 |  (action (run %{discover})))
Error: No rule found for lib/config/discover.exe
```

**Comment by astrada** [comment]
I think you also need https://pkgs.org/download/ocaml-dune-devel

But if you want to develop in OCaml, the most supported way is using [opam](http://opam.ocaml.org/).

**Comment by sergiomb2** [comment]
Thanks , with commit on master https://github.com/astrada/ocamlfuse/commit/e35e76bee3b06806256b5bfca108b7697267cd5c also use the Makefile that is in master , and with ocaml-dune-devel , I could build ocamlfuse .
So I think we should have a new release.
Thanks , best regards.
